name: Release Openshift
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version:"
        required: true
jobs:
  release-openshift:
    name: "Create Openshift releases"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ["mongodb-forks/certified-operators"]
        include:
          - repository: "mongodb-forks/certified-operators"
            certified: true
    steps:
      - name: Clone/Checkout release repository
        uses: actions/checkout@v3.5.2
        with:
          repository: ${{ matrix.repository }}
          ref: main
          path: ${{ matrix.repository }}
      - name: Clone/Checkout Atlas Operator
        uses: actions/checkout@v3.5.2
        with:
          ref: main
          path: "mongodb-atlas-kubernetes"
          fetch-depth: 0
      - name: Create release
        uses: ./mongodb-atlas-kubernetes/.github/actions/openshift-release
        with:
          version: ${{ github.event.inputs.version }}
          openshift_repository: ${{ matrix.repository }}
          certified: ${{ matrix.certified }}
          github_token: ${{ github.token }}
